server_name: "chat.local"
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names: [client, federation]
        compress: false
database:
  name: psycopg2
  args:
    user: synapse
    password: synapse_secret
    database: synapse
    host: postgres
    cp_min: 5
    cp_max: 10
media_store_path: "/data/media_store"
report_stats: false
signing_key_path: "/data/chat.local.signing.key"
registration_shared_secret: "dev_secret_key_group7"
macaroon_secret_key: "dev_macaroon_key_group7"
form_secret: "dev_form_secret_group7"
enable_registration: false
trusted_key_servers:
  - server_name: "matrix.org"
